In [2]:
import pandas as pd
import numpy as np
import glob

In [11]:
sorted_txt_files = sorted([filename for filename in glob.glob("names/*.txt")])
all_dfs = []

In [12]:
for filename in sorted_txt_files:
    # current_year is formated as "names/yobXXXX.txt", where XXXX is the year
    current_year = int(filename.split("names/yob")[1][:4])
    curr_df = pd.read_csv(filename, sep=',', names=["Name", "Gender", "Number"])
    curr_df["Year"] = current_year
    all_dfs.append(curr_df)

In [45]:
df = pd.concat(all_dfs, axis=0).sort_values(by=["Year", "Name", "Gender", "Number"]).reset_index(drop=True)

# Get the first 4 records to view the data model
df.head()

     Name Gender  Number  Year
0   Aaron      M     102  1880
1      Ab      M       5  1880
2   Abbie      F      71  1880
3  Abbott      M       5  1880
4    Abby      F       6  1880

In [46]:
# Dataset summary statistics
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Name,2085158,102449,Jessie,286,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,2085158,2,F,1227795,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Number,2085158.0,NaN,NaN,NaN,175.188734,1482.655941,5.0,7.0,12.0,32.0,99693.0
Year,2085158.0,NaN,NaN,NaN,1978.316298,34.833626,1880.0,1955.0,1988.0,2007.0,2022.0

In [47]:
# Summary stats for non-numerical columns
df.describe(exclude=np.number).T

          count  unique     top     freq
Name    2085158  102449  Jessie      286
Gender  2085158       2       F  1227795

In [48]:
# Checking for null values
df.isnull().sum()

Name      0
Gender    0
Number    0
Year      0
dtype: int64

In [49]:
# Checking for duplicate values
df.duplicated(subset=["Name", "Gender"])

Marion      284
Johnnie     284
John        284
Joseph      284
Ollie       284
           ...
Brecklin      1
Abry          1
Shinelle      1
Ivaniel       1
Diyara        1
Name: Name, Length: 80461, dtype: int64

In [51]:
# View duplicated records
dups = df[df.duplicated(subset=["Name", "Gender"])]
dups.groupby(by="Name")
print(dups["Name"].value_counts())

Marion      284
Johnnie     284
John        284
Joseph      284
Ollie       284
           ...
Brecklin      1
Abry          1
Shinelle      1
Ivaniel       1
Diyara        1
Name: Name, Length: 80461, dtype: int64

In [ ]:
df.to_csv("babyNamesSince1881.csv", index=False)